### ISSUE TITLE
TypeError is thrown when the bot received a direct message

### ISSUE THREAD

**Issue by sya-ri** [2b2tjp/2b2t.jp-bot#6]
```
[2021-03-07 04:29:54.357] main error TypeError: Cannot read property 'id' of null
at Client.client.on (/app/index.js:17:17)
                                         at Client.emit (events.js:198:13)
                                         at MessageCreateAction.handle (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
                                         at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
                                         at WebSocketManager.handlePacket (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
                                         at WebSocketShard.onPacket (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
                                         at WebSocketShard.onMessage (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
                                         at WebSocket.onMessage (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
                                         at WebSocket.emit (events.js:198:13)
                                         at Receiver.receiverOnMessage (/rbd/pnpm-volume/824596a5-1a41-4c65-879a-59b9c28b83f1/node_modules/discord.js/node_modules/ws/lib/websocket.js:825:20)
```

**Comment by acrylic-style** [comment]
you may not want to hear this but: `TypeError is thrown when the bot received a direct message` would be the correct spell

**Comment by sya-ri** [comment]
kusozako English
